#pragma once

namespace C3GA
{
	class Scalar;
	class Vector;
	class Bivector;
	class Trivector;
	class Quadvector;
	class PsuedoScalar;

	class Multivector
	{
	public:
		Multivector();
		Multivector(double _1, double e1, double e2, double e3, double no, double ni, double e1_e2, double e1_e3, double e1_no, double e1_ni, double e2_e3, double e2_no, double e2_ni, double e3_no, double e3_ni, double no_ni, double e1_e2_e3, double e1_e2_no, double e1_e2_ni, double e1_e3_no, double e1_e3_ni, double e1_no_ni, double e2_e3_no, double e2_e3_ni, double e2_no_ni, double e3_no_ni, double e1_e2_e3_no, double e1_e2_e3_ni, double e1_e2_no_ni, double e1_e3_no_ni, double e2_e3_no_ni, double e1_e2_e3_no_ni);
		Multivector(const Scalar& scalar);
		Multivector(const Vector& vector);
		Multivector(const Bivector& bivector);
		Multivector(const Trivector& trivector);
		Multivector(const Quadvector& quadvector);
		Multivector(const PsuedoScalar& psuedoscalar);
		Multivector(const Multivector& multivector);

		void Add(const Scalar& scalarA, const Scalar& scalarB);
		void Add(const Scalar& scalarA, const Vector& vectorB);
		void Add(const Scalar& scalarA, const Bivector& bivectorB);
		void Add(const Scalar& scalarA, const Trivector& trivectorB);
		void Add(const Scalar& scalarA, const Quadvector& quadvectorB);
		void Add(const Scalar& scalarA, const PsuedoScalar& psuedoscalarB);
		void Add(const Scalar& scalarA, const Multivector& multivectorB);
		void Add(const Vector& vectorA, const Scalar& scalarB);
		void Add(const Vector& vectorA, const Vector& vectorB);
		void Add(const Vector& vectorA, const Bivector& bivectorB);
		void Add(const Vector& vectorA, const Trivector& trivectorB);
		void Add(const Vector& vectorA, const Quadvector& quadvectorB);
		void Add(const Vector& vectorA, const PsuedoScalar& psuedoscalarB);
		void Add(const Vector& vectorA, const Multivector& multivectorB);
		void Add(const Bivector& bivectorA, const Scalar& scalarB);
		void Add(const Bivector& bivectorA, const Vector& vectorB);
		void Add(const Bivector& bivectorA, const Bivector& bivectorB);
		void Add(const Bivector& bivectorA, const Trivector& trivectorB);
		void Add(const Bivector& bivectorA, const Quadvector& quadvectorB);
		void Add(const Bivector& bivectorA, const PsuedoScalar& psuedoscalarB);
		void Add(const Bivector& bivectorA, const Multivector& multivectorB);
		void Add(const Trivector& trivectorA, const Scalar& scalarB);
		void Add(const Trivector& trivectorA, const Vector& vectorB);
		void Add(const Trivector& trivectorA, const Bivector& bivectorB);
		void Add(const Trivector& trivectorA, const Trivector& trivectorB);
		void Add(const Trivector& trivectorA, const Quadvector& quadvectorB);
		void Add(const Trivector& trivectorA, const PsuedoScalar& psuedoscalarB);
		void Add(const Trivector& trivectorA, const Multivector& multivectorB);
		void Add(const Quadvector& quadvectorA, const Scalar& scalarB);
		void Add(const Quadvector& quadvectorA, const Vector& vectorB);
		void Add(const Quadvector& quadvectorA, const Bivector& bivectorB);
		void Add(const Quadvector& quadvectorA, const Trivector& trivectorB);
		void Add(const Quadvector& quadvectorA, const Quadvector& quadvectorB);
		void Add(const Quadvector& quadvectorA, const PsuedoScalar& psuedoscalarB);
		void Add(const Quadvector& quadvectorA, const Multivector& multivectorB);
		void Add(const PsuedoScalar& psuedoscalarA, const Scalar& scalarB);
		void Add(const PsuedoScalar& psuedoscalarA, const Vector& vectorB);
		void Add(const PsuedoScalar& psuedoscalarA, const Bivector& bivectorB);
		void Add(const PsuedoScalar& psuedoscalarA, const Trivector& trivectorB);
		void Add(const PsuedoScalar& psuedoscalarA, const Quadvector& quadvectorB);
		void Add(const PsuedoScalar& psuedoscalarA, const PsuedoScalar& psuedoscalarB);
		void Add(const PsuedoScalar& psuedoscalarA, const Multivector& multivectorB);
		void Add(const Multivector& multivectorA, const Scalar& scalarB);
		void Add(const Multivector& multivectorA, const Vector& vectorB);
		void Add(const Multivector& multivectorA, const Bivector& bivectorB);
		void Add(const Multivector& multivectorA, const Trivector& trivectorB);
		void Add(const Multivector& multivectorA, const Quadvector& quadvectorB);
		void Add(const Multivector& multivectorA, const PsuedoScalar& psuedoscalarB);
		void Add(const Multivector& multivectorA, const Multivector& multivectorB);

		void Subtract(const Scalar& scalarA, const Scalar& scalarB);
		void Subtract(const Scalar& scalarA, const Vector& vectorB);
		void Subtract(const Scalar& scalarA, const Bivector& bivectorB);
		void Subtract(const Scalar& scalarA, const Trivector& trivectorB);
		void Subtract(const Scalar& scalarA, const Quadvector& quadvectorB);
		void Subtract(const Scalar& scalarA, const PsuedoScalar& psuedoscalarB);
		void Subtract(const Scalar& scalarA, const Multivector& multivectorB);
		void Subtract(const Vector& vectorA, const Scalar& scalarB);
		void Subtract(const Vector& vectorA, const Vector& vectorB);
		void Subtract(const Vector& vectorA, const Bivector& bivectorB);
		void Subtract(const Vector& vectorA, const Trivector& trivectorB);
		void Subtract(const Vector& vectorA, const Quadvector& quadvectorB);
		void Subtract(const Vector& vectorA, const PsuedoScalar& psuedoscalarB);
		void Subtract(const Vector& vectorA, const Multivector& multivectorB);
		void Subtract(const Bivector& bivectorA, const Scalar& scalarB);
		void Subtract(const Bivector& bivectorA, const Vector& vectorB);
		void Subtract(const Bivector& bivectorA, const Bivector& bivectorB);
		void Subtract(const Bivector& bivectorA, const Trivector& trivectorB);
		void Subtract(const Bivector& bivectorA, const Quadvector& quadvectorB);
		void Subtract(const Bivector& bivectorA, const PsuedoScalar& psuedoscalarB);
		void Subtract(const Bivector& bivectorA, const Multivector& multivectorB);
		void Subtract(const Trivector& trivectorA, const Scalar& scalarB);
		void Subtract(const Trivector& trivectorA, const Vector& vectorB);
		void Subtract(const Trivector& trivectorA, const Bivector& bivectorB);
		void Subtract(const Trivector& trivectorA, const Trivector& trivectorB);
		void Subtract(const Trivector& trivectorA, const Quadvector& quadvectorB);
		void Subtract(const Trivector& trivectorA, const PsuedoScalar& psuedoscalarB);
		void Subtract(const Trivector& trivectorA, const Multivector& multivectorB);
		void Subtract(const Quadvector& quadvectorA, const Scalar& scalarB);
		void Subtract(const Quadvector& quadvectorA, const Vector& vectorB);
		void Subtract(const Quadvector& quadvectorA, const Bivector& bivectorB);
		void Subtract(const Quadvector& quadvectorA, const Trivector& trivectorB);
		void Subtract(const Quadvector& quadvectorA, const Quadvector& quadvectorB);
		void Subtract(const Quadvector& quadvectorA, const PsuedoScalar& psuedoscalarB);
		void Subtract(const Quadvector& quadvectorA, const Multivector& multivectorB);
		void Subtract(const PsuedoScalar& psuedoscalarA, const Scalar& scalarB);
		void Subtract(const PsuedoScalar& psuedoscalarA, const Vector& vectorB);
		void Subtract(const PsuedoScalar& psuedoscalarA, const Bivector& bivectorB);
		void Subtract(const PsuedoScalar& psuedoscalarA, const Trivector& trivectorB);
		void Subtract(const PsuedoScalar& psuedoscalarA, const Quadvector& quadvectorB);
		void Subtract(const PsuedoScalar& psuedoscalarA, const PsuedoScalar& psuedoscalarB);
		void Subtract(const PsuedoScalar& psuedoscalarA, const Multivector& multivectorB);
		void Subtract(const Multivector& multivectorA, const Scalar& scalarB);
		void Subtract(const Multivector& multivectorA, const Vector& vectorB);
		void Subtract(const Multivector& multivectorA, const Bivector& bivectorB);
		void Subtract(const Multivector& multivectorA, const Trivector& trivectorB);
		void Subtract(const Multivector& multivectorA, const Quadvector& quadvectorB);
		void Subtract(const Multivector& multivectorA, const PsuedoScalar& psuedoscalarB);
		void Subtract(const Multivector& multivectorA, const Multivector& multivectorB);

		void InnerProduct(const Scalar& scalarA, const Scalar& scalarB);
		void InnerProduct(const Scalar& scalarA, const Vector& vectorB);
		void InnerProduct(const Scalar& scalarA, const Bivector& bivectorB);
		void InnerProduct(const Scalar& scalarA, const Trivector& trivectorB);
		void InnerProduct(const Scalar& scalarA, const Quadvector& quadvectorB);
		void InnerProduct(const Scalar& scalarA, const PsuedoScalar& psuedoscalarB);
		void InnerProduct(const Scalar& scalarA, const Multivector& multivectorB);
		void InnerProduct(const Vector& vectorA, const Scalar& scalarB);
		void InnerProduct(const Vector& vectorA, const Vector& vectorB);
		void InnerProduct(const Vector& vectorA, const Bivector& bivectorB);
		void InnerProduct(const Vector& vectorA, const Trivector& trivectorB);
		void InnerProduct(const Vector& vectorA, const Quadvector& quadvectorB);
		void InnerProduct(const Vector& vectorA, const PsuedoScalar& psuedoscalarB);
		void InnerProduct(const Vector& vectorA, const Multivector& multivectorB);
		void InnerProduct(const Bivector& bivectorA, const Scalar& scalarB);
		void InnerProduct(const Bivector& bivectorA, const Vector& vectorB);
		void InnerProduct(const Bivector& bivectorA, const Bivector& bivectorB);
		void InnerProduct(const Bivector& bivectorA, const Trivector& trivectorB);
		void InnerProduct(const Bivector& bivectorA, const Quadvector& quadvectorB);
		void InnerProduct(const Bivector& bivectorA, const PsuedoScalar& psuedoscalarB);
		void InnerProduct(const Bivector& bivectorA, const Multivector& multivectorB);
		void InnerProduct(const Trivector& trivectorA, const Scalar& scalarB);
		void InnerProduct(const Trivector& trivectorA, const Vector& vectorB);
		void InnerProduct(const Trivector& trivectorA, const Bivector& bivectorB);
		void InnerProduct(const Trivector& trivectorA, const Trivector& trivectorB);
		void InnerProduct(const Trivector& trivectorA, const Quadvector& quadvectorB);
		void InnerProduct(const Trivector& trivectorA, const PsuedoScalar& psuedoscalarB);
		void InnerProduct(const Trivector& trivectorA, const Multivector& multivectorB);
		void InnerProduct(const Quadvector& quadvectorA, const Scalar& scalarB);
		void InnerProduct(const Quadvector& quadvectorA, const Vector& vectorB);
		void InnerProduct(const Quadvector& quadvectorA, const Bivector& bivectorB);
		void InnerProduct(const Quadvector& quadvectorA, const Trivector& trivectorB);
		void InnerProduct(const Quadvector& quadvectorA, const Quadvector& quadvectorB);
		void InnerProduct(const Quadvector& quadvectorA, const PsuedoScalar& psuedoscalarB);
		void InnerProduct(const Quadvector& quadvectorA, const Multivector& multivectorB);
		void InnerProduct(const PsuedoScalar& psuedoscalarA, const Scalar& scalarB);
		void InnerProduct(const PsuedoScalar& psuedoscalarA, const Vector& vectorB);
		void InnerProduct(const PsuedoScalar& psuedoscalarA, const Bivector& bivectorB);
		void InnerProduct(const PsuedoScalar& psuedoscalarA, const Trivector& trivectorB);
		void InnerProduct(const PsuedoScalar& psuedoscalarA, const Quadvector& quadvectorB);
		void InnerProduct(const PsuedoScalar& psuedoscalarA, const PsuedoScalar& psuedoscalarB);
		void InnerProduct(const PsuedoScalar& psuedoscalarA, const Multivector& multivectorB);
		void InnerProduct(const Multivector& multivectorA, const Scalar& scalarB);
		void InnerProduct(const Multivector& multivectorA, const Vector& vectorB);
		void InnerProduct(const Multivector& multivectorA, const Bivector& bivectorB);
		void InnerProduct(const Multivector& multivectorA, const Trivector& trivectorB);
		void InnerProduct(const Multivector& multivectorA, const Quadvector& quadvectorB);
		void InnerProduct(const Multivector& multivectorA, const PsuedoScalar& psuedoscalarB);
		void InnerProduct(const Multivector& multivectorA, const Multivector& multivectorB);

		void OuterProduct(const Scalar& scalarA, const Scalar& scalarB);
		void OuterProduct(const Scalar& scalarA, const Vector& vectorB);
		void OuterProduct(const Scalar& scalarA, const Bivector& bivectorB);
		void OuterProduct(const Scalar& scalarA, const Trivector& trivectorB);
		void OuterProduct(const Scalar& scalarA, const Quadvector& quadvectorB);
		void OuterProduct(const Scalar& scalarA, const PsuedoScalar& psuedoscalarB);
		void OuterProduct(const Scalar& scalarA, const Multivector& multivectorB);
		void OuterProduct(const Vector& vectorA, const Scalar& scalarB);
		void OuterProduct(const Vector& vectorA, const Vector& vectorB);
		void OuterProduct(const Vector& vectorA, const Bivector& bivectorB);
		void OuterProduct(const Vector& vectorA, const Trivector& trivectorB);
		void OuterProduct(const Vector& vectorA, const Quadvector& quadvectorB);
		void OuterProduct(const Vector& vectorA, const PsuedoScalar& psuedoscalarB);
		void OuterProduct(const Vector& vectorA, const Multivector& multivectorB);
		void OuterProduct(const Bivector& bivectorA, const Scalar& scalarB);
		void OuterProduct(const Bivector& bivectorA, const Vector& vectorB);
		void OuterProduct(const Bivector& bivectorA, const Bivector& bivectorB);
		void OuterProduct(const Bivector& bivectorA, const Trivector& trivectorB);
		void OuterProduct(const Bivector& bivectorA, const Quadvector& quadvectorB);
		void OuterProduct(const Bivector& bivectorA, const PsuedoScalar& psuedoscalarB);
		void OuterProduct(const Bivector& bivectorA, const Multivector& multivectorB);
		void OuterProduct(const Trivector& trivectorA, const Scalar& scalarB);
		void OuterProduct(const Trivector& trivectorA, const Vector& vectorB);
		void OuterProduct(const Trivector& trivectorA, const Bivector& bivectorB);
		void OuterProduct(const Trivector& trivectorA, const Trivector& trivectorB);
		void OuterProduct(const Trivector& trivectorA, const Quadvector& quadvectorB);
		void OuterProduct(const Trivector& trivectorA, const PsuedoScalar& psuedoscalarB);
		void OuterProduct(const Trivector& trivectorA, const Multivector& multivectorB);
		void OuterProduct(const Quadvector& quadvectorA, const Scalar& scalarB);
		void OuterProduct(const Quadvector& quadvectorA, const Vector& vectorB);
		void OuterProduct(const Quadvector& quadvectorA, const Bivector& bivectorB);
		void OuterProduct(const Quadvector& quadvectorA, const Trivector& trivectorB);
		void OuterProduct(const Quadvector& quadvectorA, const Quadvector& quadvectorB);
		void OuterProduct(const Quadvector& quadvectorA, const PsuedoScalar& psuedoscalarB);
		void OuterProduct(const Quadvector& quadvectorA, const Multivector& multivectorB);
		void OuterProduct(const PsuedoScalar& psuedoscalarA, const Scalar& scalarB);
		void OuterProduct(const PsuedoScalar& psuedoscalarA, const Vector& vectorB);
		void OuterProduct(const PsuedoScalar& psuedoscalarA, const Bivector& bivectorB);
		void OuterProduct(const PsuedoScalar& psuedoscalarA, const Trivector& trivectorB);
		void OuterProduct(const PsuedoScalar& psuedoscalarA, const Quadvector& quadvectorB);
		void OuterProduct(const PsuedoScalar& psuedoscalarA, const PsuedoScalar& psuedoscalarB);
		void OuterProduct(const PsuedoScalar& psuedoscalarA, const Multivector& multivectorB);
		void OuterProduct(const Multivector& multivectorA, const Scalar& scalarB);
		void OuterProduct(const Multivector& multivectorA, const Vector& vectorB);
		void OuterProduct(const Multivector& multivectorA, const Bivector& bivectorB);
		void OuterProduct(const Multivector& multivectorA, const Trivector& trivectorB);
		void OuterProduct(const Multivector& multivectorA, const Quadvector& quadvectorB);
		void OuterProduct(const Multivector& multivectorA, const PsuedoScalar& psuedoscalarB);
		void OuterProduct(const Multivector& multivectorA, const Multivector& multivectorB);

		void GeometricProduct(const Scalar& scalarA, const Scalar& scalarB);
		void GeometricProduct(const Scalar& scalarA, const Vector& vectorB);
		void GeometricProduct(const Scalar& scalarA, const Bivector& bivectorB);
		void GeometricProduct(const Scalar& scalarA, const Trivector& trivectorB);
		void GeometricProduct(const Scalar& scalarA, const Quadvector& quadvectorB);
		void GeometricProduct(const Scalar& scalarA, const PsuedoScalar& psuedoscalarB);
		void GeometricProduct(const Scalar& scalarA, const Multivector& multivectorB);
		void GeometricProduct(const Vector& vectorA, const Scalar& scalarB);
		void GeometricProduct(const Vector& vectorA, const Vector& vectorB);
		void GeometricProduct(const Vector& vectorA, const Bivector& bivectorB);
		void GeometricProduct(const Vector& vectorA, const Trivector& trivectorB);
		void GeometricProduct(const Vector& vectorA, const Quadvector& quadvectorB);
		void GeometricProduct(const Vector& vectorA, const PsuedoScalar& psuedoscalarB);
		void GeometricProduct(const Vector& vectorA, const Multivector& multivectorB);
		void GeometricProduct(const Bivector& bivectorA, const Scalar& scalarB);
		void GeometricProduct(const Bivector& bivectorA, const Vector& vectorB);
		void GeometricProduct(const Bivector& bivectorA, const Bivector& bivectorB);
		void GeometricProduct(const Bivector& bivectorA, const Trivector& trivectorB);
		void GeometricProduct(const Bivector& bivectorA, const Quadvector& quadvectorB);
		void GeometricProduct(const Bivector& bivectorA, const PsuedoScalar& psuedoscalarB);
		void GeometricProduct(const Bivector& bivectorA, const Multivector& multivectorB);
		void GeometricProduct(const Trivector& trivectorA, const Scalar& scalarB);
		void GeometricProduct(const Trivector& trivectorA, const Vector& vectorB);
		void GeometricProduct(const Trivector& trivectorA, const Bivector& bivectorB);
		void GeometricProduct(const Trivector& trivectorA, const Trivector& trivectorB);
		void GeometricProduct(const Trivector& trivectorA, const Quadvector& quadvectorB);
		void GeometricProduct(const Trivector& trivectorA, const PsuedoScalar& psuedoscalarB);
		void GeometricProduct(const Trivector& trivectorA, const Multivector& multivectorB);
		void GeometricProduct(const Quadvector& quadvectorA, const Scalar& scalarB);
		void GeometricProduct(const Quadvector& quadvectorA, const Vector& vectorB);
		void GeometricProduct(const Quadvector& quadvectorA, const Bivector& bivectorB);
		void GeometricProduct(const Quadvector& quadvectorA, const Trivector& trivectorB);
		void GeometricProduct(const Quadvector& quadvectorA, const Quadvector& quadvectorB);
		void GeometricProduct(const Quadvector& quadvectorA, const PsuedoScalar& psuedoscalarB);
		void GeometricProduct(const Quadvector& quadvectorA, const Multivector& multivectorB);
		void GeometricProduct(const PsuedoScalar& psuedoscalarA, const Scalar& scalarB);
		void GeometricProduct(const PsuedoScalar& psuedoscalarA, const Vector& vectorB);
		void GeometricProduct(const PsuedoScalar& psuedoscalarA, const Bivector& bivectorB);
		void GeometricProduct(const PsuedoScalar& psuedoscalarA, const Trivector& trivectorB);
		void GeometricProduct(const PsuedoScalar& psuedoscalarA, const Quadvector& quadvectorB);
		void GeometricProduct(const PsuedoScalar& psuedoscalarA, const PsuedoScalar& psuedoscalarB);
		void GeometricProduct(const PsuedoScalar& psuedoscalarA, const Multivector& multivectorB);
		void GeometricProduct(const Multivector& multivectorA, const Scalar& scalarB);
		void GeometricProduct(const Multivector& multivectorA, const Vector& vectorB);
		void GeometricProduct(const Multivector& multivectorA, const Bivector& bivectorB);
		void GeometricProduct(const Multivector& multivectorA, const Trivector& trivectorB);
		void GeometricProduct(const Multivector& multivectorA, const Quadvector& quadvectorB);
		void GeometricProduct(const Multivector& multivectorA, const PsuedoScalar& psuedoscalarB);
		void GeometricProduct(const Multivector& multivectorA, const Multivector& multivectorB);

		double _1, e1, e2, e3, no, ni, e1_e2, e1_e3, e1_no, e1_ni, e2_e3, e2_no, e2_ni, e3_no, e3_ni, no_ni, e1_e2_e3, e1_e2_no, e1_e2_ni, e1_e3_no, e1_e3_ni, e1_no_ni, e2_e3_no, e2_e3_ni, e2_no_ni, e3_no_ni, e1_e2_e3_no, e1_e2_e3_ni, e1_e2_no_ni, e1_e3_no_ni, e2_e3_no_ni, e1_e2_e3_no_ni;
	};
}